version: '3.8'

services:
    n8n:
        image: n8nio/n8n
        restart: always
        network_mode: host
        ports:
            - '5678:5678'
        environment:
            - DB_TYPE=sqlite
            - DB_SQLITE_VACUUM_ON_STARTUP=true
        volumes:
            - n8n_data:/home/node/.n8n

volumes:
    n8n_data:
